Add: Entropy in SCS Clouds
SovereignCloudStack/standards pull request #207
Opened 2023-02-07 18:43 UTC by matfechner

Closes SovereignCloudStack/issues#234
Signed-off-by: Mathias Fechner <fechner@osism.tech>

2023-02-08 15:16 UTC, fkr commented on Design-Docs/entropy.md
> +    Keyboard Timeings.
Timeing -> timing

2023-02-08 15:18 UTC, fkr commented on Design-Docs/entropy.md
> +     A virtual instance or Virtual machines has all this radomness sources not. A instance will operate normal. But if cryptographic operations will happen,
A virtual instance or virtual machines does not have this sources for random numbers. An instance will operate normally, but if cryptographic operations will happen[...]

2023-02-08 16:01 UTC, fkr commented on Design-Docs/entropy.md
> +    HavegeD is one example which use the combination of the Linux radom device
One Procedure from the past in virtual machines or virtual appliances
is to use an entropy daemon, in order to ensure to have a sufficient amount of entropy.
Today this is a common operation although for embedded devices.
HavegeD is one example which use the combination of the Linux random device

2023-02-08 16:02 UTC, fkr commented on Design-Docs/entropy.md
> +     Modern Server CPU's of ARM, AMD and Intel shipped Hardware random
[...]ship with a hardware random[...]

2023-02-08 16:03 UTC, fkr commented on Design-Docs/entropy.md
> +     rng-utils, which will need to running.
On Baremetal-systems and virtual Instances this will require the rng-tools or 
  rng-utils to be running.

2023-02-08 16:03 UTC, fkr commented on Design-Docs/entropy.md
> +    in all Flavors have activated the relevant attributes:
All flavors will have to have the relevant attributed activated

2023-02-08 16:06 UTC, fkr commented on Design-Docs/entropy.md
> +    in SCS Cloud Infrastructures.
Images must activate the[...]
On compute nodes the rng-utils must be activated.
This is a requirement to guarantee working confident cryptography[..]

2023-02-08 16:06 UTC, fkr requested changes
Left some notes, in some cases I guessed what the outcome of the sentence should be.

2023-02-09 12:26 UTC, fkr commented on Design-Docs/entropy.md
> +    Entrophy is a concecpt that is widely used in a scope of information
"in the scope of"

2023-02-09 12:26 UTC, fkr commented on Design-Docs/entropy.md
> +    technolgy. It is a measure of the amount of disorder or radomness in
"technology. It is a measurement for the amount of"

2023-02-09 12:26 UTC, fkr commented on Design-Docs/entropy.md
> +    a system. Entrophy is used to measure the amount of information in a
"Entropy"

2023-02-09 12:28 UTC, fkr commented on Design-Docs/entropy.md
> +    in this system. For Cryptographic procedures and operation is a good
cryptographic

2023-02-09 12:29 UTC, fkr commented on Design-Docs/entropy.md
> +    In tradional Baremetal System the amount of incertitude is or was generated by the
traditional

2023-02-09 12:29 UTC, fkr commented on Design-Docs/entropy.md
> +    radonmes Ready/write cycle of the disk heads of a diskdrive, bus timings or
randomness

2023-02-09 12:29 UTC, fkr commented on Design-Docs/entropy.md
> +    Keyboard Timeings.
timings

2023-02-09 12:30 UTC, fkr commented on Design-Docs/entropy.md
> +     A virtual instance or virtual machines does not have this sources for random numbers. An instance will operate normally, but if cryptographic operations will happen, Producedures will take an ab
"these sources"

2023-02-09 12:31 UTC, fkr commented on Design-Docs/entropy.md
> +     A virtual instance or virtual machines does not have this sources for random numbers. An instance will operate normally, but if cryptographic operations will happen, Producedures will take an ab
"entropy"

2023-02-09 12:42 UTC, fkr requested changes
More wording fixes and typos.

2023-02-09 12:43 UTC, fkr commented
@matfechner I would suggest that we turn this into a branch within this repository, so that I can work directly on the branch.

2023-02-09 12:56 UTC, matfechner commented
Ok go ahead

2023-02-10 15:07 UTC, fkr commented
superseeded by https://github.com/SovereignCloudStack/standards/pull/210

2023-02-10 15:07 UTC, closed without merging