Add: Changes in linux numbergenerator
SovereignCloudStack/standards pull request #266
Opened 2023-04-25 07:35 UTC by matfechner

2023-04-28 08:52 UTC, artificial-intelligence requested changes

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +hash for entropy extraction" the full explanation will found here:
```suggestion
hash for entropy extraction" the full explanation can be found here:
```

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +[linux-rng-5.17-18](https://www.zx2c4.com/projects/linux-rng-5.17-5.18/).
maybe use a less flaky link like archive.org? this one works
```suggestion
[linux-rng-5.17-18](https://web.archive.org/web/20230321040526/https://www.zx2c4.com/projects/linux-rng-5.17-5.18/).
```

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +should not use anymore. Rng-tools can continue to be used. Rng-tools bridge the
```suggestion
This RNG improvements make some workarounds obsolete. For example haveged
should not be use anymore. Rng-tools can continue to be used. Rng-tools bridge the
```

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +These patches are now also arrived the upstream LTS Kernels.
```suggestion
These patches have now also arrived in the upstream LTS Kernels.
```

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +This behavior will look as follows:
```suggestion
The behavior will be as follows:
```

2023-04-28 08:52 UTC, artificial-intelligence commented on Standards/scs-0101-v1-entropy.md
> +because here is now working the blake2 algorithm the entropy count is sufficient.
```suggestion
because now the blake2 algorithm is used, the entropy count is sufficient.
```

2023-05-02 09:17 UTC, fkr approved these changes
With the suggested changes from @artificial-intelligence this LGTM

2023-05-03 08:59 UTC, artificial-intelligence requested changes
see the comments, the rest LGTM

2023-05-03 09:48 UTC, artificial-intelligence approved these changes
LGTM

2023-05-03 10:42 UTC, merged