Add proposal OS API and OS internal Traffic TLS encryption and PKI
SovereignCloudStack/standards pull request #370
Opened 2023-11-01 09:04 UTC by fdobrovolny

https://github.com/SovereignCloudStack/issues/issues/457

2023-11-02 09:25 UTC, fkr commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +Currently, the deployment is mostly done using [Kolla](https://opendev.org/openstack/kolla-ansible).
```suggestion
Currently, the deployment is done via [OSISM](https://github.com/osism/) which makes heavy use of [Kolla](https://opendev.org/openstack/kolla-ansible).
```

2023-11-02 09:26 UTC, fkr commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +This ADR document current status of Kolla in regard to end-to-end TLS encryption of selected OpenStack services shown below.
```suggestion
This ADR documents the current status of Kolla in regard to end-to-end TLS encryption of selected OpenStack services shown below.
```

2023-11-02 09:30 UTC, fkr commented
@artificial-intelligence can you read this and share your thoughts?

2023-11-29 10:12 UTC, artificial-intelligence requested changes
I'll add more remarks later.

Libvirt TLS is not discussed at all, so I would really at least like to see a paragraph about it.
I'll also need to check if we are missing other important services.

One thing coming to my mind is e.g. nonvnc transport encryption via vencrypt and binding of the communication channel to the novnc proxyserver, as is discussed here:

https://bugs.launchpad.net/kolla-ansible/+bug/2043709

2023-11-29 10:12 UTC, artificial-intelligence commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +Only RabbitMQ is not currently supported.
there is interest in adding an internal CA for rabbitmq and libvirt TLS support, see:

https://etherpad.opendev.org/p/kolla-caracal-ptg#L283

the problematic part currently is, choosing the appropriate CA software, which has many challenges, as can be seen in the linked document where we evaluated various alternatives.

2023-11-29 10:12 UTC, artificial-intelligence commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +[Details](https://docs.openstack.org/kolla-ansible/latest/admin/tls.html#back-end-tls-configuration)
```suggestion
[Details](https://docs.openstack.org/kolla-ansible/2023.1/admin/tls.html#back-end-tls-configuration)
```

2023-11-29 10:12 UTC, artificial-intelligence commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +Memcached does support TLS; however, this support is only [experimental](https://github.com/memcached/memcached/commit/ee1cfe3bf9384d1a93545fc942e25bed6437d910), and custom build binaries are needed.
so what do we do with this?

2023-11-29 10:12 UTC, artificial-intelligence commented on Standards/scs-XXXX-v1-encrypted-internal-openstack-traffic-and-pki-infra.md
> +
I miss a paragraph about secure libvirt live migration:

https://docs.openstack.org/nova/latest/admin/secure-live-migration-with-qemu-native-tls.html

2023-12-01 09:33 UTC, artificial-intelligence commented
another service - which is used in SCS - which is not covered here is cloudkitty, mostly used for billing purposes afaik.

see e.g. this commit to enable internal TLS usage, but the cert is not trusted during bootstrap:

https://review.opendev.org/c/openstack/kolla-ansible/+/866598

in general I would advice to go through each openstack service one-by-one and make a detailed review if the service uses any networking and what is transmitted via which network channels and which of these are already encrypted and if not why not.

So I don't know if this was already done and the above mentioned services where just missed - this would bring up the interesting question why they where missed - or if this has just not happened.

I would strongly encourage to do this, if it hasn't happened yet, because otherwise we have no complete picture and the work done here might be incomplete and ultimately lead to a false sense of security by suggesting that everything is encrypted when it really isn't.

I hope this helps, thank you all for all the work put into this so far!

2024-02-16 09:57 UTC, closed without merging